server:
  port: 5000

spring:
  datasource:
    url: jdbc:mysql://awseb-e-jrwjpwa99e-stack-awsebrdsdatabase-ai8ctbmbx5ng.ca6gxrdrgtz2.eu-central-1.rds.amazonaws.com/ebdb
    username: root
    password: asdf6541!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
